#!/bin/bash
gen-title(){
    url=$1
    #clean up that title. By default, it's a mess of hashtags and unicode.
    title=$(yt-dlp --print filename "$url" \
        | sed -e 's/#[^ ]*//g' \
        | tr -s ' ' \
        | tr ' ' '_' \
        | sed 's/.mp4$//' \
        | grep -o '[0-9a-zA-Z_.]' \
        | head -246 \
        | tr -d '\n')
    #in the off chance the title is really nothing but unicode, hashtags, and weirdness, fix it:
    [[ "${title}x" == "x" ]] && title=$(date +%s)
    #now affix the mp4 at the end if it isn't there. It shouldn't be there, but anything is possible.
    if echo "$title" | grep '.mp4$'
    then
        true
    else
        title="${title}.mp4"
    fi
}

dl(){
    url=$1
    gen-title $url
    yt-dlp -o "$title" "$url"
}

if [[ -f $1 ]]
then
    cat $1 | while read url
    do
        dl "$url"
    done
else
    dl $1
fi
